// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthorAssistant.DataAccess.Models;

public partial class AspNetUserPasskey
{
    public byte[] CredentialId { get; set; }

    public string UserId { get; set; }

    public string Data { get; set; }

    public virtual AspNetUser User { get; set; }
}