// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthorAssistant.DataAccess.Models;

public partial class BookFile
{
    public long BookFileId { get; set; }

    public long BookId { get; set; }

    public byte[] BinaryData { get; set; }

    public virtual Book Book { get; set; }
}