// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AuthorAssistant.DataAccess.Models;

public partial class Book
{
    public long BookId { get; set; }

    public string OwnerId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string TextContent { get; set; }

    public virtual ICollection<BookCoverImageConcept> BookCoverImageConcepts { get; set; } = new List<BookCoverImageConcept>();

    public virtual ICollection<BookFile> BookFiles { get; set; } = new List<BookFile>();

    public virtual ICollection<BookPromoVideo> BookPromoVideos { get; set; } = new List<BookPromoVideo>();

    public virtual AspNetUser Owner { get; set; }
}